### ISSUE TITLE
I don't have proxy and it doesn't work

### ISSUE THREAD

**Issue by LittleTerry** [Redrrx/WikimediaScrap#1]
Hi, thanks for your code. I have two questions.
1) I don't have proxy and the code said:

<img width="1175" alt="image" src="https://user-images.githubusercontent.com/19617725/230470544-164cedc5-82d4-4305-be5e-ac8d1c239ef7.png">
2) If I have proxies, what kind of format I should write in the proxies.txt file.

Many thanks!

**Comment by Redrrx** [comment]
hey there, 
format should be  ip:port  in the file but please bear in mind i only tested rotating proxies

and i have also forgotten to update the code to force you to use proxies or else it will eventually run into errors..

let me know if the format works for you, proxy type should be http or https not socks.
If not i'll update the code in few days

**Comment by LittleTerry** [comment]
> hey there, format should be ip:port in the file but please bear in mind i only tested rotating proxies
> 
> and i have also forgotten to update the code to force you to use proxies or else it will eventually run into errors..
> 
> let me know if the format works for you, proxy type should be http or https not socks. If not i'll update the code in few days

Hi, thanks for your reply. I didn't use the proxy since I don't have. I'll try it once I have proxy. Anyway, thanks for you work!
